[build]
  command = "bash ./netlify-build.sh"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  port = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
