[build]
  command = "bash ./netlify-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  port = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
